In [1]:
import numpy as np

In [8]:
a = np.zeros(5)
print(a)
print(type(a))
display(np.zeros((3,4)))
display(np.zeros((3,4,5)))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
display(np.ones(6))
display(np.ones((3,4)))
display(np.ones((3,4,5)))

array([1., 1., 1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
5 + np.zeros((3,5)) # broadcasting

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [13]:
np.empty((4,5,2))

array([[[7.22838402e-288, 4.67296746e-307],
        [1.69121096e-306, 1.24610723e-306],
        [1.11261706e-306, 7.56602523e-307],
        [7.56601165e-307, 1.89146896e-307],
        [7.56571288e-307, 3.11525958e-307]],

       [[1.24610723e-306, 1.37962320e-306],
        [1.29060871e-306, 2.22518251e-306],
        [1.33511969e-306, 1.78022342e-306],
        [1.05700345e-307, 1.00132653e-307],
        [8.01097889e-307, 1.78020169e-306]],

       [[7.56601165e-307, 1.02359984e-306],
        [8.90092016e-307, 1.02361342e-306],
        [6.89804133e-307, 8.90104239e-307],
        [8.90098127e-307, 8.90111708e-307],
        [6.23054633e-307, 9.34598926e-307]],

       [[1.42417629e-306, 1.11260687e-306],
        [9.34593493e-307, 1.33511290e-306],
        [1.33511969e-306, 2.22523140e-306],
        [6.23059726e-307, 2.22522597e-306],
        [1.06810268e-306, 2.01592676e-312]]])

In [19]:
np.linspace(2,6,10,endpoint=False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [20]:
np.linspace(2,6,10,endpoint=False,retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [22]:
np.logspace(2,5,10,base=10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [24]:
a = np.arange(16).reshape(4,4)
display(a)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
a = np.arange(4,40).reshape(6,6)
display(a)
a.max()

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

39

In [34]:
display(a.max(axis=0))#axis = 0 is row ==> comparing rowwise 4<10<16<22<28<34
display(a.max(axis=1))#axis = 1 is col ==> comparing colwise 4<5<6<7<8<9
display(10+a)
display(a/0)

array([34, 35, 36, 37, 38, 39])

array([ 9, 15, 21, 27, 33, 39])

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

C:\Users\Pallavi Prajapati\AppData\Local\Temp\ipykernel_25872\1234890741.py:4: RuntimeWarning: divide by zero encountered in divide
  display(a/0)


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [36]:
display(a ** 3)
display(pow(a,3))

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [42]:
b = np.array([2,3,1,2,3,2])
display(a+b)

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [46]:
b = b.reshape(1,-1)
display(b)
display(b.T)
display(b.T+a)

array([[2, 3, 1, 2, 3, 2]])

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [48]:
display(np.sqrt(a))
display(np.exp(a))

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

- #refer to same memory location ==> shallow copy
- #copy to another location ==> deep copy

In [50]:
x = np.array([1,2,3])
y = x                   #refer to same memory location ==> shallow copy
z = np.copy(x)          #copy to another location ==> deep copy

In [51]:
x[0] = 100
display(y)
display(z)

array([100,   2,   3])

array([1, 2, 3])

### id = return the identity of an object

In [54]:
print(id(x),id(x[0]))
print(id(y),id(y[0]))
print(id(z),id(z[0]))

249837088 15664352
249837088 15666720
16016352 15667024


In [55]:
id(x[0]) == id(y[0])

True

In [57]:
id(x[0]) == id(y[1])

True

In [56]:
id(x[0]) is id(y[0])

False

In [60]:
c = "abcd"
id(x[0]) == id(c)

False