In [71]:
import pandas as pd 

In [9]:
pd.DataFrame({
    "col1": [1,2,3,4,5],
    "col2": [2,4,6,8,9],
    "col3": "hii there first second third"
})


col1  col2                          col3
0     1     2  hii there first second third
1     2     4  hii there first second third
2     3     6  hii there first second third
3     4     8  hii there first second third
4     5     9  hii there first second third

In [10]:
df = pd.DataFrame({
    "col1": [1,2,3,4,5],
    "col2": [2,4,6,8,9],
    "col3": "hii there first second third".split()
})

In [16]:
# df['col4'] = 1
df['col4'] = df['col1'] ** 2
display(df)

col1  col2    col3  col4 col5
0     1     2     hii     1    h
1     2     4   there     4    t
2     3     6   first     9    f
3     4     8  second    16    s
4     5     9   third    25    t

In [17]:
df['col5'] = df['col3'].str[0]
display(df)

col1  col2    col3  col4 col5
0     1     2     hii     1    h
1     2     4   there     4    t
2     3     6   first     9    f
3     4     8  second    16    s
4     5     9   third    25    t

In [18]:
def test(a):
    return a**2

In [19]:
df['col4_4'] = df['col1'].apply(test)
display(df)

col1  col2    col3  col4 col5  col4_4
0     1     2     hii     1    h       1
1     2     4   there     4    t       4
2     3     6   first     9    f       9
3     4     8  second    16    s      16
4     5     9   third    25    t      25

In [20]:
def test1(a):
    if a != 's':
        return 'z'
    else:
        return 's'

In [21]:
df['col6'] = df['col5'].apply(test1)
display(df)

col1  col2    col3  col4 col5  col4_4 col6
0     1     2     hii     1    h       1    z
1     2     4   there     4    t       4    z
2     3     6   first     9    f       9    z
3     4     8  second    16    s      16    s
4     5     9   third    25    t      25    z

In [22]:
df['col6_6'] = df['col5'].apply(lambda a: 's' if a == 's' else 'z')
display(df)

col1  col2    col3  col4 col5  col4_4 col6 col6_6
0     1     2     hii     1    h       1    z      z
1     2     4   there     4    t       4    z      z
2     3     6   first     9    f       9    z      z
3     4     8  second    16    s      16    s      s
4     5     9   third    25    t      25    z      z

In [24]:
df['col7'] = df['col3'].apply(len)
display(df)

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7
0     1     2     hii     1    h       1    z      z     3
1     2     4   there     4    t       4    z      z     5
2     3     6   first     9    f       9    z      z     5
3     4     8  second    16    s      16    s      s     6
4     5     9   third    25    t      25    z      z     5

In [26]:
import math
df['col8'] = df['col2'].apply(math.log2) # any log acan be applied
display(df)

col1  col2    col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1     2     hii     1    h       1    z      z     3  1.000000
1     2     4   there     4    t       4    z      z     5  2.000000
2     3     6   first     9    f       9    z      z     5  2.584963
3     4     8  second    16    s      16    s      s     6  3.000000
4     5     9   third    25    t      25    z      z     5  3.169925

# numpy numerical python

In [70]:
import numpy as np

In [31]:
l = ["pallavi",1,3,4,5]
print(type(l))
print(type(np.array(l))) # ndarray means is n dimentional array
np.array(l)

<class 'list'>
<class 'numpy.ndarray'>


array(['pallavi', '1', '3', '4', '5'], dtype='<U11')

In [39]:
a1 = np.array([3,4,1,6,7,3.6])
print(a1)
a = np.array([[1,2],[3,4]])
display(a)

[3.  4.  1.  6.  7.  3.6]


array([[1, 2],
       [3, 4]])

In [41]:
display(a[1][1])
display(a1[1])

4

4.0

In [44]:
a2 = np.array([1,2,3,4,],ndmin=4)
display(a2)
display(a2[0])
display(a2[0][0])
display(a2[0][0][0])
display(a2[0][0][0][0])


array([[[[1, 2, 3, 4]]]])

array([[[1, 2, 3, 4]]])

array([[1, 2, 3, 4]])

array([1, 2, 3, 4])

1

In [46]:
display(np.asanyarray([1,3,4,5,6])) 
display(np.asarray([1,2,3,4,5,6]))

array([1, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [47]:
display(np.mat([1,3,4,5,6]))

matrix([[1, 3, 4, 5, 6]])

In [49]:
a = [1,3,4,5,6]                     #list
display(np.asarray(a))
display(np.asanyarray(a))
display(np.mat(a))
display(np.asanyarray(np.mat(a)))   # not coverting to array as matrix is subclaas of array
display(np.asarray(np.mat(a)))

array([1, 3, 4, 5, 6])

array([1, 3, 4, 5, 6])

matrix([[1, 3, 4, 5, 6]])

matrix([[1, 3, 4, 5, 6]])

array([[1, 3, 4, 5, 6]])

In [60]:
arr = np.fromfunction(lambda i,j : i == j, (3,3))
display(arr)
arr1 = np.fromfunction(lambda i,j: i*j, (4,4))
display(arr1)
arr1 = np.fromfunction(lambda i,j: i*j, (4,4),dtype=int)
display(np.mat(arr1))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

#### (3,3,2) --> means 3 matrix of dimension is 3 row 2 col or (3*2) (if x,y,z is 3d axis then visualize (3,3,2) as (z,y,x))

In [76]:
# (3,3,2) --> means 3 matrix of dimension is 3 row 2 col or (3*2) (if x,y,z is 3d axis then visualize (3,3,2) as (z,y,x))
arr2 = np.fromfunction(lambda i,j,z: i*j*z, (3,3,2),dtype=int)
display(arr2)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [77]:
arr2.reshape(6,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4]])

In [78]:
 # (4,3,2,2) --> means 4 combination 3such array of dimension 2 row 2 col or (2*2))
arr3 = np.fromfunction(lambda i,j,z,p: i*j*z*p, (4,3,2,2),dtype=int)
display(arr3)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [67]:
display(arr2.ndim)# number of axis
display(arr2.size)# number of element
display(arr2.shape)# give dimension
display(arr2.dtype)#datatype of array

3

18

(3, 3, 2)

dtype('int32')

variety of ways to have huge dataframe

In [ ]:
pd.DataFrame(arr2) # error not more than 2d it allows 

In [69]:
arr = np.fromfunction(lambda i,j : i == j, (300,500))
display(pd.DataFrame(arr))

0      1      2      3      4      5      6      7      8      9    \
0     True  False  False  False  False  False  False  False  False  False   
1    False   True  False  False  False  False  False  False  False  False   
2    False  False   True  False  False  False  False  False  False  False   
3    False  False  False   True  False  False  False  False  False  False   
4    False  False  False  False   True  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
295  False  False  False  False  False  False  False  False  False  False   
296  False  False  False  False  False  False  False  False  False  False   
297  False  False  False  False  False  False  False  False  False  False   
298  False  False  False  False  False  False  False  False  False  False   
299  False  False  False  False  False  False  False  False  False  False   

     ...    490    491    492    493    494    495    496    497    498    499  
0    ...  False  False  False  False  False  False  False  False  False  False  
1    ...  False  False  False  False  False  False  False  False  False  False  
2    ...  False  False  False  False  False  False  False  False  False  False  
3    ...  False  False  False  False  False  False  False  False  False  False  
4    ...  False  False  False  False  False  False  False  False  False  False  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
295  ...  False  False  False  False  False  False  False  False  False  False  
296  ...  False  False  False  False  False  False  False  False  False  False  
297  ...  False  False  False  False  False  False  False  False  False  False  
298  ...  False  False  False  False  False  False  False  False  False  False  
299  ...  False  False  False  False  False  False  False  False  False  False  

[300 rows x 500 columns]

In [72]:
np.random.rand(100,4) # randomly generate 100*4 array 

array([[0.38990929, 0.97755219, 0.12029141, 0.74230236],
       [0.11766277, 0.96735351, 0.32833674, 0.53244522],
       [0.54747806, 0.83748284, 0.67626035, 0.48468404],
       [0.70645475, 0.40384852, 0.54024773, 0.27817869],
       [0.96452576, 0.54695174, 0.12935294, 0.2802617 ],
       [0.85650811, 0.49425662, 0.01343156, 0.40904317],
       [0.45832279, 0.93134973, 0.88732446, 0.50565634],
       [0.11649474, 0.8230947 , 0.34217991, 0.74261802],
       [0.69629442, 0.57214629, 0.09549185, 0.30092758],
       [0.89968724, 0.08476303, 0.87745183, 0.18509272],
       [0.88358026, 0.40158729, 0.77299811, 0.81390859],
       [0.83078236, 0.2524156 , 0.04180347, 0.11117669],
       [0.28146079, 0.52669473, 0.55155962, 0.27179628],
       [0.08136986, 0.56998709, 0.19762751, 0.29085078],
       [0.75945358, 0.98285096, 0.35138533, 0.05908165],
       [0.58114972, 0.10202207, 0.65217651, 0.61463558],
       [0.78941698, 0.01465731, 0.01888182, 0.31735853],
       [0.526059  , 0.30878572,

In [73]:
np.random.randint(4,50)#rand int between 4 to 50

29

In [74]:
np.random.randn(4,5) #random number with normal distribution as standard deviation = 1 and average = 0 

array([[ 0.00367689,  2.41771125, -1.2985913 ,  0.88299236, -0.16880445],
       [-0.57688858, -0.91947756, -1.55966113, -1.11043081,  0.49083846],
       [-0.06008193,  2.09429552,  1.15620605, -1.01556068,  0.36235468],
       [ 0.60781877,  0.3251884 , -0.70082624, -1.26000133, -0.52772926]])

In [75]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -1.628504  0.795209  0.467509  1.358892 -0.172284
1  0.680459  1.269223 -0.350017  1.292824  0.117646
2 -0.574275 -0.051504  1.850489 -2.356781  1.646177
3 -0.195355  0.675376 -1.836911  0.227701  2.093893

#### change dimention of data

In [ ]:
arr2.reshape(6,3)# from 3d to 2d

In [79]:
pd.DataFrame(arr2.reshape(6,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4

In [80]:
arr2.reshape(6,-1) # any negative number can be usd to reshape and find next factor of number so as to be total number in array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4]])

In [85]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [86]:
np.arange(4,10,.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [87]:
np.arange(4,10,.2)[1:7]

array([4.2, 4.4, 4.6, 4.8, 5. , 5.2])

In [89]:
arr4 = np.random.rand(4,5)
display(arr4)

array([[0.13078207, 0.76077403, 0.63047509, 0.66041509, 0.24705262],
       [0.0773629 , 0.88459003, 0.56797777, 0.33116667, 0.06180705],
       [0.79114198, 0.49272587, 0.01029335, 0.36274914, 0.95735534],
       [0.36315038, 0.66440909, 0.69063554, 0.81644549, 0.05163834]])

In [92]:
arr4[arr4 > .5]

array([0.76077403, 0.63047509, 0.66041509, 0.88459003, 0.56797777,
       0.79114198, 0.95735534, 0.66440909, 0.69063554, 0.81644549])

In [93]:
arr4[[1,2],[2]]

array([0.56797777, 0.01029335])

In [98]:
arr4[1:4, 0:4]

array([[0.0773629 , 0.88459003, 0.56797777, 0.33116667],
       [0.79114198, 0.49272587, 0.01029335, 0.36274914],
       [0.36315038, 0.66440909, 0.69063554, 0.81644549]])

In [101]:
a2 = arr4[1:4, [0,1,2,3]]

In [104]:
a2[0][0] = 10000
a2[0][0]

10000.0

In [107]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

In [111]:
display(a*b) # indexwise multiplication
m = a@b# matrix multiplication

array([[ 2,  6],
       [12, 20]])

In [112]:
m/0

C:\Users\Pallavi Prajapati\AppData\Local\Temp\ipykernel_21688\3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])